# ======================================
#  HTTPS (porta 8100)
# ======================================

server.port=8100
server.ssl.enabled=true
server.ssl.key-store=classpath:webserver-keystore.p12
server.ssl.key-store-password=sdpassword
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=webserver

#  HTTP ativo na porta 8080 está implementado em HttpAndHttpsConfig.java
